Pixelplus SDK: cimage::CImageDisplayerCPP Class Reference
cimage::CImageDisplayerCPP Class Reference
RAII C++ wrapper around the C ABI. No rendering; forwards to C API.
#include <CImageDisplayerCPP.h>
Public Member Functions
CImageDisplayerCPP ()
Construct and allocate an instance. Throws std::bad_alloc on failure.
~CImageDisplayerCPP ()
Destroy the owned instance.
CImageDisplayerCPP (CImageDisplayerCPP &&o) noexcept
Move construct, transferring ownership.
CImageDisplayerCPP & operator= (CImageDisplayerCPP &&o) noexcept
Move assign, destroying any currently owned handle.
void setImage (const csh_img::CSH_Image &img, csh_img::CopyMode mode=csh_img::CopyMode::Shallow)
Set image from csh_img::CSH_Image with copy semantics.
void setImageRaw (uint32_t w, uint32_t h, CImgFormat fmt, CImgPattern pat, CImgAlign align, const void *pixels, size_t bytes, CImgCopyMode mode)
Set image from a raw pointer (when not using CSH_Image).
void setViewport (int w, int h)
Set viewport size in pixels.
void setFitMode (FitMode m)
Set fit strategy (None/Fit/Fill/Stretch).
void setDimensionality (Dimensionality d)
Switch between 2D and 3D modes.
void set2DAnchor (float ax, float ay)
Set normalized anchor inside image rect [0..1]².
void set2DTranslation (float tx, float ty)
Set 2D translation in viewport pixels.
void set2DScale (float sx, float sy)
Set 2D scale factors.
void set2DRotationDeg (float deg)
Set rotation in degrees (CCW).
void reset2D ()
Reset 2D transform to identity.
void set3DModelTranslate (float x, float y, float z)
Set model translation.
void set3DModelScale (float x, float y, float z)
Set model scale.
void set3DModelRotationQuat (float w, float x, float y, float z)
Set model rotation (quaternion).
void reset3DModel ()
Reset model transform to identity.
void set3DTarget (float x, float y, float z)
Set look-at target.
void set3DEye (float x, float y, float z)
Set camera eye.
void set3DUp (float x, float y, float z)
Set camera up vector.
void set3DOrbitStyle (CImgOrbitStyle s)
Set orbit interaction style.
void setOrtho (float l, float r, float b, float t, float n, float f)
Set orthographic projection.
void setPerspective (float fovyDeg, float aspect, float zNear, float zFar)
Set perspective projection (fovy in degrees).
void model2D_3x3 (float outRowMajor3x3[9]) const
Fetch current 2D model (row-major 3×3).
void model3D_4x4 (float outColMajor4x4[16]) const
Fetch current 3D model (column-major 4×4).
void view3D_4x4 (float outColMajor4x4[16]) const
Fetch current 3D view (column-major 4×4).
void proj_4x4 (float outColMajor4x4[16]) const
Fetch current projection (column-major 4×4).
void mvp3D_4x4 (float outColMajor4x4[16]) const
Fetch current MVP = P*V*M (column-major 4×4).
void triStrip2D_XYUV (float out4x4[16]) const
Transformed quad as 2D tri-strip with UVs ({x,y,u,v} per vertex).
CImageUploadDesc uploadDesc () const
Current upload descriptor (pointer/size/stride/layout).
void beginPointer (float x, float y, MouseButton btn, KeyMod keyMods)
Begin a pointer interaction.
void updatePointer (float x, float y)
Update pointer position during active interaction.
void endPointer ()
End current pointer interaction.
void wheelScroll (float delta, float cx, float cy)
Mouse wheel / trackpad zoom or dolly.
void keyPan2D (float dx, float dy)
Keyboard panning in 2D mode (pixels).
void keyDolly3D (float amount)
Keyboard dolly in 3D mode (world units along view).
CImageDisplayerHandle raw () const noexcept
Expose raw C handle for low-level interop.
Static Public Member Functions
static void triStrip3D_XYUV_ObjectSpace (float out4x4[16])
Unit quad in object space for 3D pipelines ({x,y,u,v} per vertex).
Detailed Description
RAII C++ wrapper around the C ABI. No rendering; forwards to C API.
This wrapper creates/destroys the underlying C instance and offers typed helpers. ABI remains stable because the boundary stays in C.
Definition at line 98 of file CImageDisplayerCPP.h.
Member Function Documentation
setImage()
void cimage::CImageDisplayerCPP::setImage (const csh_img::CSH_Image & img, csh_img::CopyMode mode = csh_img::CopyMode::Shallow) inline
Set image from csh_img::CSH_Image with copy semantics.
Parameters
img Source image.
mode Copy mode (MetaOnly/Shallow/Deep). Default Shallow.
Definition at line 125 of file CImageDisplayerCPP.h.
{
            const auto fmt = static_cast<CImgFormat>(static_cast<uint32_t>(img.getFormat()));
            const auto pat = static_cast<CImgPattern>(static_cast<uint32_t>(img.getPattern()));
            const auto alg = static_cast<CImgAlign>(static_cast<uint32_t>(img.getMemoryAlign()));
            const void* data = nullptr;
            size_t bytes = 0;
            if (mode != csh_img::CopyMode::MetaOnly) {
                data = img.data();
                bytes = img.getBufferSize();
            }
            cimgSetImageRaw(h_, img.getWidth(), img.getHeight(), fmt, pat, alg, data, bytes,
                static_cast<CImgCopyMode>(static_cast<uint32_t>(mode)));
        }
References csh_img::CSH_Image::data(), csh_img::CSH_Image::getBufferSize(), csh_img::CSH_Image::getFormat(), csh_img::CSH_Image::getHeight(), csh_img::CSH_Image::getMemoryAlign(), csh_img::CSH_Image::getPattern(), and csh_img::CSH_Image::getWidth().
setImageRaw()
void cimage::CImageDisplayerCPP::setImageRaw (uint32_t w, uint32_t h, CImgFormat fmt, CImgPattern pat, CImgAlign align, const void * pixels, size_t bytes, CImgCopyMode mode) inline
Set image from a raw pointer (when not using CSH_Image).
Parameters
w,h Dimensions in pixels.
fmt Format.
pat Pattern / channel order.
align Memory packing/alignment.
pixels Pointer to buffer (nullable for MetaOnly).
bytes Total buffer size.
mode Copy semantics.
Definition at line 150 of file CImageDisplayerCPP.h.
{
            cimgSetImageRaw(h_, w, h, fmt, pat, align, pixels, bytes, mode);
        }
wheelScroll()
void cimage::CImageDisplayerCPP::wheelScroll (float delta, float cx, float cy) inline
Mouse wheel / trackpad zoom or dolly.
Parameters
delta Positive for zoom/dolly in.
cx,cy Cursor at event time (pixels).
Definition at line 240 of file CImageDisplayerCPP.h.
{ cimgWheelScroll(h_, delta, cx, cy); }
The documentation for this class was generated from the following file:
CImageDisplayer/CImageDisplayerCPP.h