Pixelplus SDK: csh_img::CSH_Image Class Reference
csh_img::CSH_Image Class Reference
Image container with explicit format metadata and flexible buffer ownership.
#include <CSH_Image.h>
Public Types
using byte = uint8_t
Unsigned 8-bit byte alias for buffer access.
Public Member Functions
CSH_Image ()
Constructs an empty, disabled image (no buffer).
CSH_Image (uint32_t width, uint32_t height, En_ImageFormat format, bool alloc_mem=true, uint32_t image_count=1)
Constructs an image with metadata and optional allocation.
CSH_Image (const CSH_Image &)=default
Shallow copy (shared buffer).
CSH_Image (CSH_Image &&) noexcept=default
Move constructor.
CSH_Image & operator= (const CSH_Image &)=default
Shallow assignment (shared buffer).
CSH_Image & operator= (CSH_Image &&) noexcept=default
Move assignment.
void copy (const CSH_Image &src, CopyMode mode)
Copies metadata and optionally buffer depending on mode.
void copyBufferPointer (const CSH_Image &src)
Shares the underlying buffer pointer/view with src (shallow ownership).
void copyBufferPointer (byte *pFrame)
Adopts an external raw pointer as the buffer (shallow, no delete).
void saveImage (const std::filesystem::path &filepath) const
Saves the image (header + fields + optional bytes) to a file.
void loadImage (const std::filesystem::path &filepath)
Loads an image from a TLV file written by saveImage().
uint32_t getWidth () const
uint32_t getHeight () const
bool isEnabled () const
uint32_t getCameraId () const
En_ImageFormat getFormat () const
uint32_t getMemoryBit () const
uint32_t getOriginalBit () const
En_ImagePattern getPattern () const
En_ImageMemoryAlign getMemoryAlign () const
std::size_t getBufferSize () const
uint32_t getImageCount () const
uint32_t getSelectedImage () const
byte * data ()
Returns a pointer to the current view (selected image).
const byte * data () const
Returns a const pointer to the current view (selected image).
byte * getImagePtr (uint32_t n)
Returns the base pointer to the n-th image (0-based) without changing state.
const byte * getImagePtr (uint32_t n) const
Returns the base pointer to the n-th image (0-based) without changing state.
void setSelectedImage (uint32_t idx)
Selects the active image index for the view.
std::size_t totalBytes () const
Logical total bytes = per-frame bytes ¡¿ image count.
void recomputeBufferSize ()
Recomputes buffer_size based on format, width, height, and bit depth.
void allocateBuffer ()
Allocates exactly totalBytes() and updates the current view.
Backward-compatible overloads
Public Attributes
uint32_t width = 0
Image width in pixels.
uint32_t height = 0
Image height in pixels.
bool bEnable = false
Logical enabled flag.
uint32_t camera_id = 0
User-defined camera identifier.
En_ImageFormat format = En_ImageFormat::Gray8
Current image format.
uint32_t memory_bit = 8
Memory container bit depth.
uint32_t original_bit = 8
Original sensor bit depth.
En_ImagePattern pattern = En_ImagePattern::RGGB
Pixel/component layout.
En_ImageMemoryAlign memory_align = En_ImageMemoryAlign::Packed
Memory layout.
std::size_t buffer_size = 0
Per-frame byte size.
uint32_t image_count = 1
Number of images in allocation.
uint32_t sel_image = 0
Currently selected image index.
std::shared_ptr< byte[]> buffer
Base shared buffer pointer (may be null).
Detailed Description
Image container with explicit format metadata and flexible buffer ownership.
Key properties
Ownership: buffer is stored as std::shared_ptr<byte[]>. Shallow copies share the buffer; deep copies require a pre-allocated destination.
View: buffer_offset + sel_image define the current view inside a multi-image allocation (e.g., frame arrays).
Persistence: TLV-based binary I/O (saveImage/loadImage) with a stable header.
Interoperability: Optional zero-copy interop with OpenCV (when CSH_IMAGE_WITH_OPENCV).
Warning
Deep copies require the destination to have an allocated buffer with enough writable bytes from the current view; otherwise an exception is thrown.
Definition at line 129 of file CSH_Image.h.
Constructor & Destructor Documentation
CSH_Image()
csh_img::CSH_Image::CSH_Image (uint32_t width, uint32_t height, En_ImageFormat format, bool alloc_mem = true, uint32_t image_count = 1)
Constructs an image with metadata and optional allocation.
Parameters
width Image width in pixels.
height Image height in pixels.
format Pixel/container format.
alloc_mem If true, allocate a buffer sized to width*height*bpp*image_count.
image_count Number of images (frames) in the allocation.
Note
The per-frame byte size is computed by recomputeBufferSize().
References format, height, image_count, and width.
Member Function Documentation
allocateBuffer()
void csh_img::CSH_Image::allocateBuffer ()
Allocates exactly totalBytes() and updates the current view.
Exceptions
std::runtime_error If buffer_size or image_count is zero.
On success, sets buffer_capacity_bytes, ensures sel_image is in range, and updates buffer_offset accordingly.
copy()
void csh_img::CSH_Image::copy (const CSH_Image & src, CopyMode mode)
Copies metadata and optionally buffer depending on mode.
CopyMode::MetaOnly : copies metadata; resets buffer.
CopyMode::Shallow : shares src buffer; adopts capacity info if known.
CopyMode::Deep : copies bytes into existing destination buffer.
Parameters
src Source image.
mode Copy behavior.
Exceptions
std::runtime_error If mode is Deep and the destination has no buffer or insufficient writable bytes from current view.
std::invalid_argument If mode is unknown.
References copy(), and CSH_Image().
Referenced by copy().
copyBufferPointer() [1/2]
void csh_img::CSH_Image::copyBufferPointer (byte * pFrame)
Adopts an external raw pointer as the buffer (shallow, no delete).
Parameters
pFrame Raw pointer to externally-managed memory.
Exceptions
std::invalid_argument If pFrame is nullptr.
Warning
The memory is not freed by this class. Ensure the lifetime of pFrame outlives this image or any shared copies.
References copyBufferPointer().
copyBufferPointer() [2/2]
void csh_img::CSH_Image::copyBufferPointer (const CSH_Image & src)
Shares the underlying buffer pointer/view with src (shallow ownership).
Parameters
src Source image (its buffer/shared_ptr is adopted).
References copyBufferPointer(), and CSH_Image().
Referenced by copyBufferPointer(), and copyBufferPointer().
data() [1/2]
byte * csh_img::CSH_Image::data () inline
Returns a pointer to the current view (selected image).
Returns
Writable pointer or nullptr if no buffer.
Definition at line 260 of file CSH_Image.h.
{ return buffer ? (buffer.get() + buffer_offset) : nullptr; }
References buffer.
Referenced by cimage::CImageDisplayerCPP::setImage().
data() [2/2]
const byte * csh_img::CSH_Image::data () const inline
Returns a const pointer to the current view (selected image).
Returns
Read-only pointer or nullptr if no buffer.
Definition at line 266 of file CSH_Image.h.
{ return buffer ? (buffer.get() + buffer_offset) : nullptr; }
References buffer.
getBufferSize()
std::size_t csh_img::CSH_Image::getBufferSize () const inline
Returns
Per-frame byte size.
Definition at line 250 of file CSH_Image.h.
{ return buffer_size; }
References buffer_size.
Referenced by cimage::CImageDisplayerCPP::setImage().
getCameraId()
uint32_t csh_img::CSH_Image::getCameraId () const inline
Returns
Associated camera identifier (user-defined).
Definition at line 238 of file CSH_Image.h.
{ return camera_id; }
References camera_id.
getFormat()
En_ImageFormat csh_img::CSH_Image::getFormat () const inline
Returns
Current image format.
Definition at line 240 of file CSH_Image.h.
{ return format; }
References format.
Referenced by cimage::CImageDisplayerCPP::setImage().
getHeight()
uint32_t csh_img::CSH_Image::getHeight () const inline
Returns
Image height in pixels.
Definition at line 234 of file CSH_Image.h.
{ return height; }
References height.
Referenced by cimage::CImageDisplayerCPP::setImage().
getImageCount()
uint32_t csh_img::CSH_Image::getImageCount () const inline
Returns
Number of images in the allocation.
Definition at line 252 of file CSH_Image.h.
{ return image_count; }
References image_count.
getImagePtr() [1/2]
byte * csh_img::CSH_Image::getImagePtr (uint32_t n)
Returns the base pointer to the n-th image (0-based) without changing state.
Parameters
n Image index.
Returns
Pointer to the start of image n or nullptr if no buffer.
Exceptions
std::out_of_range If n >= image_count.
getImagePtr() [2/2]
const byte * csh_img::CSH_Image::getImagePtr (uint32_t n) const
Returns the base pointer to the n-th image (0-based) without changing state.
Parameters
n Image index.
Returns
Pointer to the start of image n or nullptr if no buffer.
Exceptions
std::out_of_range If n >= image_count.
getMemoryAlign()
En_ImageMemoryAlign csh_img::CSH_Image::getMemoryAlign () const inline
Returns
Memory alignment/plane arrangement.
Definition at line 248 of file CSH_Image.h.
{ return memory_align; }
References memory_align.
Referenced by cimage::CImageDisplayerCPP::setImage().
getMemoryBit()
uint32_t csh_img::CSH_Image::getMemoryBit () const inline
Returns
Container bit depth (memory).
Definition at line 242 of file CSH_Image.h.
{ return memory_bit; }
References memory_bit.
getOriginalBit()
uint32_t csh_img::CSH_Image::getOriginalBit () const inline
Returns
Original sensor bit depth (semantic).
Definition at line 244 of file CSH_Image.h.
{ return original_bit; }
References original_bit.
getPattern()
En_ImagePattern csh_img::CSH_Image::getPattern () const inline
Returns
Pixel pattern (CFA/YUV order/channel order).
Definition at line 246 of file CSH_Image.h.
{ return pattern; }
References pattern.
Referenced by cimage::CImageDisplayerCPP::setImage().
getSelectedImage()
uint32_t csh_img::CSH_Image::getSelectedImage () const inline
Returns
Currently selected image index (0-based).
Definition at line 254 of file CSH_Image.h.
{ return sel_image; }
References sel_image.
getWidth()
uint32_t csh_img::CSH_Image::getWidth () const inline
Returns
Image width in pixels.
Definition at line 232 of file CSH_Image.h.
{ return width; }
References width.
Referenced by cimage::CImageDisplayerCPP::setImage().
isEnabled()
bool csh_img::CSH_Image::isEnabled () const inline
Returns
Whether the image is logically enabled/valid.
Definition at line 236 of file CSH_Image.h.
{ return bEnable; }
References bEnable.
loadImage()
void csh_img::CSH_Image::loadImage (const std::filesystem::path & filepath)
Loads an image from a TLV file written by saveImage().
Parameters
filepath Source path.
Exceptions
std::runtime_error On I/O errors, bad magic/version, or allocation failures.
References loadImage(), and saveImage().
Referenced by loadImage().
recomputeBufferSize()
void csh_img::CSH_Image::recomputeBufferSize ()
Recomputes buffer_size based on format, width, height, and bit depth.
Uses bytesPerPixelForFormat() when known; otherwise falls back to ceil(memory_bit/8) bytes per pixel.
saveImage()
void csh_img::CSH_Image::saveImage (const std::filesystem::path & filepath) const
Saves the image (header + fields + optional bytes) to a file.
Parameters
filepath Destination path.
Exceptions
std::runtime_error On I/O errors or when the buffer is missing but required.
Format: Magic (CHSI) + Version + field count + {TLV...}. The buffer is written as a single field when present. All integers are little-endian.
References saveImage().
Referenced by loadImage(), and saveImage().
setSelectedImage()
void csh_img::CSH_Image::setSelectedImage (uint32_t idx)
Selects the active image index for the view.
Parameters
idx New index (0-based).
Exceptions
std::out_of_range If idx >= image_count or if the computed offset exceeds capacity.
totalBytes()
std::size_t csh_img::CSH_Image::totalBytes () const inline
Logical total bytes = per-frame bytes ¡¿ image count.
Returns
Total logical size of the allocation.
Definition at line 293 of file CSH_Image.h.
{ return buffer_size * static_cast<std::size_t>(image_count); }
References buffer_size, and image_count.
The documentation for this class was generated from the following file:
utility/CSH_Image/CSH_Image.h